version: '3.8'

services:
  gpt4eval:
    build: .
    volumes:
      - ./assets:/opt/gpt4eval/assets
    secrets:
      - OPENAI_API_KEY
    environment:
      - DATASET_NAME

secrets:
  OPENAI_API_KEY:
    file: ./secrets/OPENAI_API_KEY
